### ISSUE TITLE
reduce top + bottom padding in header to 12px

### ISSUE THREAD

**Issue by jdrewsmith** [braindumpapp/braindumpapp.github.io#22]
<img width="1364" alt="screen shot 2017-06-21 at 10 47 19 pm" src="https://user-images.githubusercontent.com/2482376/27415214-cd2d1712-56d3-11e7-9e94-a19d2f949238.png">

**Comment by jdrewsmith** [comment]
Is there a way to center the "Join the Waitlist" button vertically too that would be 💯

**Comment by TYMichaelChen** [comment]
@jdrewsmith I'm not sure if I fixed the issue with this. Let me know if this still needs some fixing
